### ISSUE TITLE
Person entity default constructor

### ISSUE THREAD

**Issue by syeds-git** [Baeldung/kotlin-tutorials#162]
I see that in your example for JPA the person object is created using an ID of 0. I thought that with the jpa plugin we can create person using no-arg constructor Person() and then set the other properties except for ID. Please clarify if providing default ID's at object creation time is the only way to work with Kotlin & JPA?

**Comment by kwoyke** [comment]
Hi @syeds-git,
Can you please clarify which article you're referring to?

**Comment by syeds-git** [comment]
https://www.baeldung.com/kotlin/jpa

**Comment by kwoyke** [comment]
We fixed the code and updated the article.
