### ISSUE TITLE
Current implementation of LoggingResponseDecorator may log uninitialized headers

### ISSUE THREAD

**Issue by ygreyeb** [Baeldung/kotlin-tutorials#259]
During instantiation of the `LoggingResponseDecorator`, you are logging the headers of the response.
https://github.com/Baeldung/kotlin-tutorials/blob/5368ede9a9dc249366f8c83860482ba4210e63f6/spring-reactive-kotlin/src/main/kotlin/com/baeldung/logfilter/decorator/LoggingResponseDecorator.kt#L29

At that point the headers may not be initialized or fully committed. Besides, if I wanted to log the status code of the response, that would also be undefined at that stage. I have only tested this on the Java version of this code, but invoking the `beforeCommit` delegate method worked for me:
````java
public LoggingResponseDecorator(ServerHttpResponse delegate) {
    super(delegate);
    beforeCommit(() -> Mono.fromRunnable(() -> {
        if (log.isDebugEnabled()) {
            log.debug("{} {}", getStatusCode(), getHeaders());
        }
    }));
}
````

Sorry to create an issue of this, but the [blog entry](https://www.baeldung.com/kotlin/spring-webflux-log-request-response-body) has the comments disabled.

**Comment by kwoyke** [comment]
Thanks for the feedback @ygreyeb. We'll take a look into this.

**Comment by kwoyke** [comment]
We fixed the code and updated the article @ygreyeb.
