### ISSUE TITLE
Which license governs the kotlin-tutorials?

### ISSUE THREAD

**Issue by rzheleva** [Baeldung/kotlin-tutorials#48]
Hi Team, 

May you please advise which license governs the kotlin-tutorials repo/project?

Thanks, 
Radi

**Comment by rzheleva** [comment]
Hi Team,

We would like to contribute to the project, but before we submit a PR we would like to make sure that we understand which license is governing kotlin-tutorials. 

Please advise, 
Radi

**Comment by rzheleva** [comment]
Hi Team,

May you please advise which license governs the kotlin-tutorials repo/project?

Thanks,
Radi

**Comment by rzheleva** [comment]
Hello Team, 

May you please advise which license governs the kotlin-tutorials repo/project? And may you please post the project's open-source license in the project documentation?

Thanks, 
Radi

**Comment by kwoyke** [comment]
Hi,

This repository serves only code examples presented on the baeldung.com site. Basically, only Baeldung's authors should contribute.

Hope this makes sense.
