### ISSUE TITLE
Guide to Spring Boot Testing

### ISSUE THREAD

**Issue by don41382** [Baeldung/kotlin-tutorials#854]
Hey @SmartyAnsh,

Thanks for the great article about [Spring Boot Testing](https://www.baeldung.com/kotlin/spring-boot-testing). I am working with gradle / kotlin setup and could not get your test setup working. I always got the error:

```
kotlin.UninitializedPropertyAccessException: lateinit property mockMvc has not been initialized
```

I don't know if this is just gradle specific, but in order to get kotest / funspec working with spring boot, I had to add:

```
override fun extensions() = listOf(io.kotest.extensions.spring.SpringExtension)
```

to my test. Than everything worked. Here is my demo controller test as an example:

```
@WebMvcTest
@ContextConfiguration
class DemoControllerTest : FunSpec() {
    override fun extensions() = listOf(io.kotest.extensions.spring.SpringExtension)

    @Autowired
    private lateinit var mockMvc: MockMvc

    init {
        test("index") {
            mockMvc.get("/hello").andReturn().response.contentAsString shouldBe "hello"
        }
    }
}
```

**Comment by apeterlic** [comment]
Hey @don41382,

This seems like an issue with your custom application setup and not the code maintained by us.
In this case, I suggest going through StackOverflow; this is a great place to ask more general questions.

Regards,
Team.
